/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bbms;
import javax.swing.JTable;
import java.sql.*;
import javax.swing.JOptionPane;
import bbms.dbConnection;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author Acer
 */
public class SearchBloodDonarLocation extends javax.swing.JFrame {

    /**
     * Creates new form SearchBloodDonarLocation
     */
    
    DefaultTableModel model=null;
    
    public SearchBloodDonarLocation() {
        initComponents();
        setRecordTOTabel();
    }
    
    
    public void setRecordTOTabel(){
        try{
        Connection con=dbConnection.getCon();
        PreparedStatement pst=con.prepareStatement("select * from adddonar");
        ResultSet rs= pst.executeQuery();
        while(rs.next()){
          
           String FullName=rs.getString("FullName");
           String FatherName=rs.getString("FatherName");
           String MotherName=rs.getString("MotherName");
            String Age=rs.getString("Age");
             String Mobile=rs.getString("Mobile");
              String Gender=rs.getString("Gender");
               String Email=rs.getString("Email");
                String BloodGroup=rs.getString("BloodGroup");
                 String Province=rs.getString("Province");
                  String Address=rs.getString("Address");
                  
                  Object[] obj={FullName,FatherName,MotherName,Age,Mobile,Gender,Email,BloodGroup,Province,Address};
                 
                  model=(DefaultTableModel)TableInfo.getModel();
                  model.addRow(obj);
        }
    }
        catch(Exception e){
            e.printStackTrace();
        }
    }
    
public void search(String str){
    model=(DefaultTableModel) TableInfo.getModel();
    TableRowSorter<DefaultTableModel> trs=new TableRowSorter<>(model);
    TableInfo.setRowSorter(trs);
  trs.setRowFilter(RowFilter.regexFilter(str));
}
    
//    public void donar(){
//        String address=search.getText();
//    DefaultTableModel dtm=(DefaultTableModel)TableInfo.getModel();
//    dtm.setRowCount(0);
//    try{
//       Connection con=dbConnection.getCon();
//            Statement stmt = con.createStatement();
//            ResultSet rs=stmt.executeQuery("select * from adddonar where province like '%"+address+"%' or Address like'%"+address+"%' ");
//            while(rs.next()){
//
//dtm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
//              
//            }
//    }
//    catch(Exception e){
//        
//    }
//}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableInfo = new javax.swing.JTable();
        jSeparator3 = new javax.swing.JSeparator();
        PrintBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(370, 200));
        setMaximumSize(new java.awt.Dimension(800, 602));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Heading.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        Heading.setText("Search Blood Donar(Address)");
        getContentPane().add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 23, 644, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 788, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/location.png"))); // NOI18N
        jLabel2.setText("Search");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 101, 123, -1));

        txt_search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 98, 158, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 160, 788, 10));

        TableInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FullName", "FatherName", "MotherName", "Age", "Mobile", "Gender", "Email", "BloodGroup", "Province", "Address"
            }
        ));
        jScrollPane1.setViewportView(TableInfo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 176, 722, 257));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 466, 788, 10));

        PrintBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PrintBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/print.png"))); // NOI18N
        PrintBtn.setText("Print");
        PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PrintBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 509, -1, -1));

        CloseBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CloseBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close.png"))); // NOI18N
        CloseBtn.setText("Close");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 509, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bg.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 602));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 800, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintBtnActionPerformed
        // TODO add your handling code here:
        try{
           TableInfo.print(JTable.PrintMode.NORMAL);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_PrintBtnActionPerformed

    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseBtnActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        
       String searchString= txt_search.getText().toLowerCase();
       search(searchString);
        
//        try{
//           Connection con=dbConnection.getCon();
//            Statement stmt = con.createStatement(); 
//            ResultSet rs=stmt.executeQuery("select * from adddonar where province like '%"+address+"%' or Address like'%"+address+"%' ");
//            JOptionPane.showMessageDialog(null,"Search");
//            TableInfo.setAutoResizeMode(TableInfo.AUTO_RESIZE_OFF);
//            TableModel dbConnection = null;
//            JOptionPane.showMessageDialog(null,"Searching");
////            ResultSet rs=stmt.executeQuery("select * from adddonar where province like '%"+address+"%' or Address like'%"+address+"%' ");
//            while(rs.next()){

//dtm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
              
//          TableInfo.setModel(dbConnection.r);

        
        

//    DefaultTableModel dtm=(DefaultTableModel)TableInfo.getModel();
//    dtm.setRowCount(0);
//    try{
//       Connection con=dbConnection.getCon();
//            Statement stmt = con.createStatement();
//            JOptionPane.showMessageDialog(null,"Searching");
//            ResultSet rs=stmt.executeQuery("select * from adddonar where province like '%"+address+"%' or Address like'%"+address+"%' ");
//            JOptionPane.showMessageDialog(null,"Search");
//            while(rs.next()){
//JOptionPane.showMessageDialog(null,"Enter");
//dtm.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10)});
//              
//            }
//    }
//    catch(Exception e){
//        JOptionPane.showMessageDialog(null,"not enter");
//    }
    }//GEN-LAST:event_txt_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchBloodDonarLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchBloodDonarLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchBloodDonarLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchBloodDonarLocation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchBloodDonarLocation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton PrintBtn;
    private javax.swing.JTable TableInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
