/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package blood.bank.management.system;

/**
 *
 * @author Acer
 */
import bbms.Adddonar;
import bbms.dbConnection;
import java.sql.*;
//import Connect.dbConnection;
import javax.swing.JOptionPane;
public class AddDonar extends javax.swing.JPanel {

    /**
     * Creates new form AddDonar
     */
    public AddDonar() {
        initComponents();
        try{
//        
            Connection con=dbConnection.getCon();
             Statement stmt=con.createStatement();
            
       
        ResultSet rs= stmt.executeQuery("select count(id) from adddonar");
        if(rs.next())
        {
            int id=rs.getInt(1);
            id= id+1;
            String str= String.valueOf(id);
            idText.setText(str);
            
        }
        else
            idText.setText("1");
        
        } 
        catch(Exception e)
        {
         JOptionPane.showMessageDialog(null, e);
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        FatherName = new javax.swing.JLabel();
        MotherName = new javax.swing.JLabel();
        DOB = new javax.swing.JLabel();
        MobileNumber = new javax.swing.JLabel();
        Gender = new javax.swing.JLabel();
        idText = new javax.swing.JLabel();
        FText = new javax.swing.JTextField();
        FaText = new javax.swing.JTextField();
        MoText = new javax.swing.JTextField();
        MpText = new javax.swing.JTextField();
        MBtn = new javax.swing.JRadioButton();
        FBtn = new javax.swing.JRadioButton();
        OBtn = new javax.swing.JRadioButton();
        Email = new javax.swing.JLabel();
        BloodGroup = new javax.swing.JLabel();
        City = new javax.swing.JLabel();
        CompleteAddress = new javax.swing.JLabel();
        EText = new javax.swing.JTextField();
        BText = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        CoText = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        Resetbtn = new javax.swing.JButton();
        AgeText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Exitbtn = new javax.swing.JButton();
        CText = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(700, 500));
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(800, 600));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("New Donar Id");

        FullName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FullName.setText("Full Name");

        FatherName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FatherName.setText("Father Name");

        MotherName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MotherName.setText("Mother Name");

        DOB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DOB.setText("Age");

        MobileNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MobileNumber.setText("Mobile Number");

        Gender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Gender.setText("Gender");

        idText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FaText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaTextActionPerformed(evt);
            }
        });

        MoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        MpText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MpTextActionPerformed(evt);
            }
        });

        MBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MBtn.setText("Male");
        MBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBtnActionPerformed(evt);
            }
        });

        FBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FBtn.setText("Female");

        OBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        OBtn.setText("Other");
        OBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OBtnActionPerformed(evt);
            }
        });

        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setText("Email");

        BloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BloodGroup.setText("Blood Group");

        City.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        City.setText("City");

        CompleteAddress.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CompleteAddress.setText("Complete Address");

        EText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ETextActionPerformed(evt);
            }
        });

        BText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        BText.setBorder(null);
        BText.setOpaque(true);

        CoText.setColumns(20);
        CoText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CoText.setRows(5);
        jScrollPane1.setViewportView(CoText);

        jLabel2.setFont(new java.awt.Font("Algerian", 1, 36)); // NOI18N
        jLabel2.setText("ADD NEW DONAR");

        Savebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Savebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/save.png"))); // NOI18N
        Savebtn.setText("SAVE");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        Resetbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Resetbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/reset.png"))); // NOI18N
        Resetbtn.setText("RESET");
        Resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetbtnActionPerformed(evt);
            }
        });

        AgeText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        Exitbtn.setBackground(new java.awt.Color(255, 153, 153));
        Exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Exitbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        Exitbtn.setText("EXIT");
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        CText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bagmati ", "Gandaki", " Lumbini ", "Karnali ", "Sudurpashchim ", "Madhesh ", "Province 1" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)
                        .addGap(49, 49, 49)
                        .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MotherName)
                            .addComponent(DOB)
                            .addComponent(MobileNumber)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(FatherName)
                                    .addGap(19, 19, 19))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MoText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MpText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(FaText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FText, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(MBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(FBtn)
                                        .addGap(6, 6, 6)
                                        .addComponent(OBtn))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Savebtn)
                                .addGap(145, 145, 145))))
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CompleteAddress)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(City)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(BloodGroup)
                                            .addGap(37, 37, 37))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(Email)
                                            .addGap(86, 86, 86))))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(Resetbtn)
                                .addGap(154, 154, 154))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Exitbtn)
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(206, 206, 206)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(246, 246, 246)
                                    .addComponent(jLabel3)))
                            .addGap(0, 167, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jSeparator2)))
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Exitbtn)
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FullName)
                        .addGap(31, 31, 31)
                        .addComponent(FatherName)
                        .addGap(29, 29, 29)
                        .addComponent(MotherName)
                        .addGap(34, 34, 34)
                        .addComponent(DOB)
                        .addGap(33, 33, 33)
                        .addComponent(MobileNumber)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MBtn)
                                .addComponent(Gender))
                            .addComponent(FBtn)
                            .addComponent(OBtn)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(FText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(FaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(MoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(MpText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Email)
                                .addGap(28, 28, 28)
                                .addComponent(BloodGroup)
                                .addGap(29, 29, 29)
                                .addComponent(City))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(BText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(CText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(CompleteAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savebtn)
                    .addComponent(Resetbtn))
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jLabel2)
                    .addGap(104, 104, 104)
                    .addComponent(jLabel3)
                    .addGap(304, 304, 304)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void FaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaTextActionPerformed

    private void MpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MpTextActionPerformed

    private void MBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MBtnActionPerformed

    private void OBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OBtnActionPerformed

    private void ETextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ETextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ETextActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
  String id=idText.getText();
        String fullName=FText.getText();
        String fatherName=FaText.getText();
        String motherName=MoText.getText();
        String age=AgeText.getText();

        String number=MpText.getText();
        String Gender = null ;
        if(MBtn.isSelected()){
            Gender="male";
        }
        else if(FBtn.isSelected()){
            Gender="female";
        }
        else if(OBtn.isSelected()){
            Gender="other";
        }
        String email=EText.getText();
        String bloodgrp=(String)BText.getSelectedItem();
        String province=(String)CText.getSelectedItem();
        String coAddr=CoText.getText();
        
        try{

            Connection con=dbConnection.getCon();
             Statement stmt=con.createStatement();
           
            JOptionPane.showMessageDialog(null, "Connected");

         stmt.executeUpdate("insert into bloodbankmanagement.adddonar(id,FullName,FatherName,MotherName,Age,Mobile,Gender,Email,BloodGroup,Province,Address) values('"+id+"','"+fullName+"','"+fatherName+"','"+motherName+"','"+age+"','"+number+"','"+Gender+"','"+email+"','"+bloodgrp+"','"+province+"','"+coAddr+"')");
                 JOptionPane.showMessageDialog(null, "added sucessfully");
                 setVisible(false);
                 new Adddonar().setVisible(true);
        }
        catch(Exception ex){
           System.out.println(ex);
                        JOptionPane.showMessageDialog(null, "Error adding donar");
                }
             
             

//try{
//Class.forName("com.mysql.cj.jdbc.Driver");
//java.sql.Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bloodbankmanagement","root","binam12345@");
//   JOptionPane.showMessageDialog(null, "connected");
//}
//catch(Exception e){
//     JOptionPane.showMessageDialog(null, "notconnected");
//}
    }//GEN-LAST:event_SavebtnActionPerformed

    private void ResetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetbtnActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new AddDonar().setVisible(true);
    }//GEN-LAST:event_ResetbtnActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
        // TODO add your handling code here:
        
        int a= JOptionPane.showConfirmDialog(null, "Do you want to close the form","Select",JOptionPane.YES_NO_CANCEL_OPTION);
       if(a==0){
           this.setVisible(false);
            new HomePage().setVisible(true);
       }
        
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        // TODO add your handling code here:
//        try{
//           Connection con=dbConnection.getCon();
//           Statement st=con.createStatement();
//           ResultSet rs=st.executeQuery("select max(id) from adddonar");
//           if(rs.first()){
//               int id=rs.getInt(1);
//               id=id+1;
//               String str=String.valueOf(id);
//               idText.setText(str);
//           }
//           else{
//              idText.setText("1");
//           }
//        }
//        catch(Exception e){
//            JOptionPane.showMessageDialog(null, e);
//        }
    }//GEN-LAST:event_jPanel1ComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        try{
           Connection con=dbConnection.getCon();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("select max(id) from adddonar");
           if(rs.first()){
               int id=rs.getInt(1);
               id=id+1;
               String str=String.valueOf(id);
               idText.setText(str);
           }
           else{
              idText.setText("1");
           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgeText;
    private javax.swing.JComboBox<String> BText;
    private javax.swing.JLabel BloodGroup;
    private javax.swing.JComboBox<String> CText;
    private javax.swing.JLabel City;
    private javax.swing.JTextArea CoText;
    private javax.swing.JLabel CompleteAddress;
    private javax.swing.JLabel DOB;
    private javax.swing.JTextField EText;
    private javax.swing.JLabel Email;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JRadioButton FBtn;
    private javax.swing.JTextField FText;
    private javax.swing.JTextField FaText;
    private javax.swing.JLabel FatherName;
    private javax.swing.JLabel FullName;
    private javax.swing.JLabel Gender;
    private javax.swing.JRadioButton MBtn;
    private javax.swing.JTextField MoText;
    private javax.swing.JLabel MobileNumber;
    private javax.swing.JLabel MotherName;
    private javax.swing.JTextField MpText;
    private javax.swing.JRadioButton OBtn;
    private javax.swing.JButton Resetbtn;
    private javax.swing.JButton Savebtn;
    private javax.swing.JLabel idText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
