/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blood.bank.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JLabel();
        OutPutPanel = new javax.swing.JPanel();
        MenuBar = new javax.swing.JMenuBar();
        Donar = new javax.swing.JMenu();
        AddNew = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Update = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        AllDonar = new javax.swing.JMenuItem();
        Search = new javax.swing.JMenu();
        Location = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        BloodGroup = new javax.swing.JMenuItem();
        Stock = new javax.swing.JMenu();
        INcreased = new javax.swing.JMenuItem();
        Decreased = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        Details = new javax.swing.JMenuItem();
        Delete = new javax.swing.JMenu();
        DeleteDonar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        Request = new javax.swing.JMenu();
        Exit = new javax.swing.JMenu();
        Logout = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        ExitApp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        setSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Background.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 990));

        OutPutPanel.setMaximumSize(new java.awt.Dimension(846, 586));
        OutPutPanel.setMinimumSize(new java.awt.Dimension(846, 586));
        OutPutPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(OutPutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 50, -1, -1));

        MenuBar.setBackground(new java.awt.Color(255, 204, 204));
        MenuBar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        MenuBar.setMargin(new java.awt.Insets(2, 2, 2, 2));
        MenuBar.setPreferredSize(new java.awt.Dimension(465, 50));

        Donar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Donar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/heart.png"))); // NOI18N
        Donar.setText("Donar");
        Donar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Donar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Donar.setIconTextGap(7);
        Donar.setMargin(new java.awt.Insets(4, 4, 4, 4));

        AddNew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AddNew.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add.png"))); // NOI18N
        AddNew.setText("Add New");
        AddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewActionPerformed(evt);
            }
        });
        Donar.add(AddNew);
        Donar.add(jSeparator1);

        Update.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/updated.png"))); // NOI18N
        Update.setText("Update Details");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        Donar.add(Update);
        Donar.add(jSeparator6);

        AllDonar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        AllDonar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllDonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/AllDonar.png"))); // NOI18N
        AllDonar.setText("All Donar Details");
        AllDonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllDonarActionPerformed(evt);
            }
        });
        Donar.add(AllDonar);

        MenuBar.add(Donar);

        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/search (1).png"))); // NOI18N
        Search.setText("Search Blood Donar");
        Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Location.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Location.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Location.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/location.png"))); // NOI18N
        Location.setText("Location");
        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });
        Search.add(Location);
        Search.add(jSeparator2);

        BloodGroup.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_DOWN_MASK));
        BloodGroup.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BloodGroup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/blood-type.png"))); // NOI18N
        BloodGroup.setText("Blood Group");
        BloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodGroupActionPerformed(evt);
            }
        });
        Search.add(BloodGroup);

        MenuBar.add(Search);

        Stock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/candlestick.png"))); // NOI18N
        Stock.setText("Stock");
        Stock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Stock.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        INcreased.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        INcreased.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        INcreased.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/increase.png"))); // NOI18N
        INcreased.setText("Increased");
        INcreased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INcreasedActionPerformed(evt);
            }
        });
        Stock.add(INcreased);

        Decreased.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Decreased.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Decreased.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/decrese.png"))); // NOI18N
        Decreased.setText("Decresed");
        Decreased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreasedActionPerformed(evt);
            }
        });
        Stock.add(Decreased);
        Stock.add(jSeparator3);

        Details.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        Details.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/details.png"))); // NOI18N
        Details.setText("Details");
        Details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailsActionPerformed(evt);
            }
        });
        Stock.add(Details);

        MenuBar.add(Stock);

        Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete.png"))); // NOI18N
        Delete.setText("Delete Donar");
        Delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        DeleteDonar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DeleteDonar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteDonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete.png"))); // NOI18N
        DeleteDonar.setText("Delete Donar");
        DeleteDonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteDonarActionPerformed(evt);
            }
        });
        Delete.add(DeleteDonar);
        Delete.add(jSeparator4);

        MenuBar.add(Delete);

        Request.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Request.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Request.png"))); // NOI18N
        Request.setText("Donation");
        Request.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Request.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestActionPerformed(evt);
            }
        });
        MenuBar.add(Request);

        Exit.setBackground(new java.awt.Color(255, 204, 204));
        Exit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/exit .png"))); // NOI18N
        Exit.setText("Exit");
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout.png"))); // NOI18N
        Logout.setText("LogOut");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Exit.add(Logout);
        Exit.add(jSeparator5);

        ExitApp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ExitApp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cancel.png"))); // NOI18N
        ExitApp.setText("Exit Application");
        ExitApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitAppActionPerformed(evt);
            }
        });
        Exit.add(ExitApp);

        MenuBar.add(Exit);

        setJMenuBar(MenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new UpdateDetails());
       Background.setVisible(false);
    }//GEN-LAST:event_UpdateActionPerformed

    private void BloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodGroupActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new SearchBloodGroup());
//       Background.setVisible(false);
    }//GEN-LAST:event_BloodGroupActionPerformed

    private void DeleteDonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteDonarActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new DeleteDonar());
       Background.setVisible(false);
    }//GEN-LAST:event_DeleteDonarActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You really want to LOGOUT","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            setVisible(false);
            new LoginPage().setVisible(true);
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void ExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitAppActionPerformed
        // TODO add your handling code here:
        int a=JOptionPane.showConfirmDialog(null, "Do You really want to Close Application","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        } 
    }//GEN-LAST:event_ExitAppActionPerformed

    private void AddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewActionPerformed
        // TODO add your handling code here:
//         OutPutPanel.add(new AllDonar());
//           BACKGROUND.setVisible(false);
        OutPutPanel.add(new AddDonar());
       Background.setVisible(false);
        
    }//GEN-LAST:event_AddNewActionPerformed

    private void AllDonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllDonarActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new AllDonarDetail());
       Background.setVisible(false);
    }//GEN-LAST:event_AllDonarActionPerformed

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new SearchBloodDonar());
       Background.setVisible(false);
    }//GEN-LAST:event_LocationActionPerformed

    private void INcreasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INcreasedActionPerformed
        // TODO add your handling code here:OutPutPanel.add(new SearchBloodDonar());
       OutPutPanel.add(new StockIncrease());
       Background.setVisible(false);
    }//GEN-LAST:event_INcreasedActionPerformed

    private void DecreasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreasedActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new StockDecreased());
       Background.setVisible(false);
    }//GEN-LAST:event_DecreasedActionPerformed

    private void DetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailsActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new StockDetail());
       Background.setVisible(false);
    }//GEN-LAST:event_DetailsActionPerformed

    private void RequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestActionPerformed
        // TODO add your handling code here:
        OutPutPanel.add(new StockDetail());
         Background.setVisible(false);
         
    }//GEN-LAST:event_RequestActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddNew;
    private javax.swing.JMenuItem AllDonar;
    private javax.swing.JLabel Background;
    private javax.swing.JMenuItem BloodGroup;
    private javax.swing.JMenuItem Decreased;
    private javax.swing.JMenu Delete;
    private javax.swing.JMenuItem DeleteDonar;
    private javax.swing.JMenuItem Details;
    private javax.swing.JMenu Donar;
    private javax.swing.JMenu Exit;
    private javax.swing.JMenuItem ExitApp;
    private javax.swing.JMenuItem INcreased;
    private javax.swing.JMenuItem Location;
    private javax.swing.JMenuItem Logout;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel OutPutPanel;
    private javax.swing.JMenu Request;
    private javax.swing.JMenu Search;
    private javax.swing.JMenu Stock;
    private javax.swing.JMenuItem Update;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
